"""dont delete review

Revision ID: 04412999af1f
Revises: 
Create Date: 2026-02-22 11:05:53.405895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04412999af1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely."""

    # --- 1️⃣ Fix NULL likes sebelum dijadikan NOT NULL ---
    op.execute(
        "UPDATE haikus SET likes = 0 WHERE likes IS NULL"
    )

    op.alter_column(
        'haikus',
        'likes',
        existing_type=sa.INTEGER(),
        nullable=False
    )

    # --- 2️⃣ Haiku created_at -> timezone aware + NOT NULL ---
    op.execute("UPDATE haikus SET created_at = now() WHERE created_at IS NULL")
    op.alter_column(
        'haikus',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False
    )

    # --- 3️⃣ OTP user_id jadi NOT NULL (safe guard dulu) ---
    op.execute(
        "DELETE FROM otps WHERE user_id IS NULL"
    )

    op.alter_column(
        'otps',
        'user_id',
        existing_type=sa.UUID(),
        nullable=False
    )

    # --- 4️⃣ Review created_at tetap timezone aware (NO downgrade) ---
    op.alter_column(
        'reviews',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )

    # --- 5️⃣ Users age numeric -> integer ---
    op.alter_column(
        'users',
        'age',
        existing_type=sa.NUMERIC(),
        type_=sa.Integer(),
        existing_nullable=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('otps', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('haikus', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('haikus', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
